CPP = g++
CPPFLAGS = -std=c++17 -Wall -Werror -pedantic -o

mytree:
	 gcc -o mytree.x mytree.c

mytime:
	$(CPP) $(CPPFLAGS) mytime.x mytime.c

mymtimes:
	$(CPP) $(CPPFLAGS) mymtimes.x mymtimes.c

clean:
	rm -v *.x
