C = gcc
FLAGS = -std=gnu99 -Wall -pedantic -g

mytree: mytree.c
	$(C) $(FLAGS) mytree.c -o mytree.x
mytime: mytime.c
	$(C) $(FLAGS) mytime.c -o mytime.x
mymtimes: mymtimes.c
	$(C) $(FLAGS) mymtimes.c -o mymtimes.x
remove:
	rm -rf *.x